const titles = [
    "How to get started with Date Object",
    "Understanding Closures in JavaScript",
    "Mastering Async/Await",
    "The Power of Prototypes",
    "JavaScript ES6 Features You Should Know",
    "Event Loop and Concurrency in JavaScript",
    "Understanding Hoisting in JavaScript",
    "How 'this' Works in JavaScript",
    "JavaScript Higher-Order Functions Explained",
    "Promises vs. Async/Await: What's the Difference?",
    "Understanding Scope and Lexical Scope",
    "JavaScript Callbacks: What You Need to Know",
    "Deep Dive into JavaScript Objects",
    "JavaScript Destructuring and Spread Operator",
    "Introduction to Functional Programming in JavaScript",
    "Understanding the Fetch API",
    "JavaScript Modules: CommonJS vs ES Modules",
    "How to Use Map, Filter, and Reduce",
    "Mastering JavaScript Generators",
    "JavaScript Memory Management and Garbage Collection",
    "Understanding Symbol and WeakMap",
    "JavaScript Proxy and Reflect API",
    "Deep Dive into JavaScript WeakSet and WeakMap",
    "What is Currying in JavaScript?",
    "Understanding the Debounce and Throttle Functions",
    "JavaScript Error Handling: Try, Catch, and Finally",
    "How to Optimize JavaScript Performance",
    "Understanding the JavaScript Prototype Chain",
    "Using JavaScript for DOM Manipulation",
    "JavaScript Data Structures: Arrays and Objects",
    "How to Work with WebSockets in JavaScript",
    "JavaScript Regular Expressions (RegEx) Explained",
    "JavaScript Type Coercion and Comparisons",
    "Understanding the JavaScript Set Object",
    "Deep Dive into JavaScript Weak References",
    "How to Use the Intersection Observer API",
    "JavaScript and the Shadow DOM",
    "Understanding Web Components with JavaScript",
    "How to Create a Custom Event in JavaScript",
    "A Guide to JavaScript Decorators",
    "How to Use the JavaScript Clipboard API",
    "JavaScript Proxy API for Beginners",
    "How to Work with IndexedDB in JavaScript",
    "Understanding JavaScript Service Workers",
    "How to Implement Lazy Loading in JavaScript",
    "JavaScript Data Structures: Maps and Sets",
    "Introduction to JavaScript Streams",
    "How to Create a JavaScript Drag and Drop Feature",
    "JavaScript Form Validation Best Practices",
    "A Guide to JavaScript Design Patterns",
    "Understanding JavaScript Async Generators",
    "How to Work with the File API in JavaScript",
    "JavaScript and WebAssembly: What You Need to Know",
    "How to Create an Infinite Scroll in JavaScript",
    "Using JavaScript with the Canvas API",
    "JavaScript Testing with Jest",
    "JavaScript UI Frameworks: React vs Vue vs Angular",
    "A Guide to Writing Clean JavaScript Code",
    "How to Use JavaScript for Web Scraping",
    "JavaScript Performance Optimization Techniques",
    "Introduction to TypeScript: JavaScript's Superset",
    "Using JavaScript with GraphQL",
    "JavaScript Debugging Tips and Tricks",
    "Understanding JavaScript WeakMap and WeakSet",
    "How to Build a REST API with JavaScript",
    "Introduction to Node.js for JavaScript Developers",
    "Understanding Express.js Middleware",
    "How to Build a Full-Stack App with MERN",
    "How to Use Sequelize with Node.js",
    "Building a Chat App with Socket.io",
    "Understanding Event Emitters in Node.js",
    "Using Streams in Node.js",
    "JavaScript Authentication with JWT",
    "How to Build a Secure API with Node.js",
    "Understanding CORS in JavaScript",
    "How to Work with MongoDB in JavaScript",
    "JavaScript Security Best Practices",
    "Using Web Workers for Multithreading in JavaScript",
    "How to Build a PWA with JavaScript",
    "JavaScript Internationalization (i18n) Basics",
    "A Guide to JavaScript Animations with GSAP",
]

module.exports = titles