const quotes = [
    "True love is built on a foundation of trust, understanding, and mutual respect.",
    "Every great relationship is defined by the strength of its communication and support.",
    "Love is not just about being with someone, but about growing together through life.",
    "In any relationship, kindness and patience will go further than words ever will.",
    "The most successful relationships are those where both people are equally invested.",
    "A relationship is a partnership where love, trust, and respect thrive above all else.",
    "When both partners are committed to understanding each other, love flourishes.",
    "The key to a lasting relationship is mutual growth, communication, and shared dreams.",
    "In love, it's the small gestures that speak the loudest and create the deepest bonds.",
    "True love is not just about moments of happiness, but about facing challenges together.",
    "Love is an ongoing process of learning, growing, and supporting one another through life.",
    "A loving relationship requires two people who choose to be their best selves every day.",
    "The most powerful relationships are built on unwavering trust, honesty, and open hearts.",
    "Respect and love are the cornerstones of any successful and meaningful relationship.",
    "The strength of a relationship is found in how well you work together through difficulties.",
    "In love, the ability to compromise and grow together is what creates lasting happiness.",
    "A great relationship is based on shared values, mutual respect, and deep emotional connection.",
    "In the right relationship, you feel supported, encouraged, and deeply understood at all times.",
    "The foundation of a healthy relationship is rooted in trust, patience, and constant support.",
    "Love is not perfect; it's about finding someone who accepts you, flaws and all, with care.",
    "Success is not measured by the heights we reach, but by the strength of the foundation we build.",
    "True success is found in the joy of meaningful work and the love we give and receive.",
    "To work towards success is to constantly redefine what you value in life.",
    "Power is not in dominance, but in the ability to inspire and uplift others.",
    "Success is often a reflection of persistence, dedication, and a willingness to adapt.",
    "The power of integrity lies in staying true to your principles, even when no one is watching.",
    "True power comes from helping others rise, not from pushing them down.",
    "In work, it’s the ethical choices we make that determine the true value of our actions.",
    "Great relationships and great success are built on mutual respect, shared goals, and love.",
    "Trust is the most valuable currency in both relationships and in the pursuit of success.",
    "A relationship based on honesty fosters the trust that success and love thrive on.",
    "When work and passion are aligned, success becomes an inevitable outcome.",
    "A partnership where both individuals grow together is the key to both happiness and success.",
    "The power of love is not in its ability to change others, but in its ability to change ourselves.",
    "Success is not a destination, but a journey shared with those who matter the most.",
    "You don’t build success in isolation; you build it with others by your side.",
    "Work towards a success that aligns with your values, and you’ll never work a day in your life.",
    "Every action has a ripple effect. Live ethically, and the world will reflect it back to you.",
    "Success is found in doing what you love, with the people you love, for reasons that matter.",
    "Great work is achieved not by force, but by creating an environment where creativity can thrive.",
    "True power is the ability to make a difference in the lives of those around you.",
    "Success without integrity is just an empty achievement.",
    "Love and ethics are the foundation of any meaningful success or lasting power.",
    "The true strength of any individual or relationship lies in their ability to adapt to challenges.",
    "Work with purpose, love with passion, and live with integrity for lasting success.",
    "Success comes from the balance of desire, effort, and ethical choices.",
    "To lead with power, one must first lead with integrity and respect for others.",
    "A relationship that fosters growth and support is one that will see long-term success.",
    "True success is not about wealth, but about living a life of purpose and ethical contribution.",
    "The foundation of a successful career and fulfilling relationships is the same: respect and trust.",
    "The power of an individual is in their capacity to create meaningful change in the world around them.",
    "Great leaders understand the importance of both relationships and work in achieving long-lasting success.",
    "Success in relationships comes from the commitment to continuously improve, listen, and understand.",
    "In both love and work, the power to influence comes from empathy, kindness, and integrity.",
    "Success comes when we stop comparing ourselves to others and start focusing on our own growth.",
    "A relationship without mutual respect is like a career without passion: both are destined to falter.",
    "To succeed, it’s not just about what you do, but why you do it and the values that guide you.",
    "True success is not in what we achieve, but in the lives we touch along the way.",
    "The most successful people are not those who work hardest, but those who work smartest with integrity.",
    "Power comes not from controlling others, but from empowering them to be their best selves.",
    "A successful relationship is one where both partners feel seen, heard, and valued.",
    "Integrity in work and love creates a ripple effect that touches everyone around us.",
    "Great success comes from the ability to navigate life with honesty, resilience, and love.",
    "Work is most meaningful when it serves a greater purpose, aligned with your values and passions.",
    "Love is not about finding perfection, but about embracing each other's imperfections with grace.",
    "True love is an ethical commitment, where respect and care for each other guide every action.",
    "Great relationships and work are both built on a shared commitment to mutual growth and respect.",
    "Success is not about the recognition you receive, but the positive impact you create.",
    "True power comes from knowing your worth and using it to lift others up.",
    "Integrity in your work is the foundation for achieving success and living with purpose.",
    "True love grows stronger through challenges, and so does success when it’s built on perseverance.",
    "Every great achievement is a product of hard work, but it is also a reflection of ethical choices.",
    "Success is not just about what you achieve, but the integrity with which you achieve it.",
    "A partnership is most powerful when both people are equally invested in its success and growth.",
    "Success doesn’t happen overnight. It’s the result of constant effort, integrity, and passion.",
    "True love is an ethical commitment to constantly grow together, supporting one another through everything.",
    "In any meaningful work, success is defined by the positive difference you make in the world.",
    "The key to true power lies in your ability to listen, understand, and act with integrity.",
    "In both work and love, patience and resilience are the cornerstones of long-term success.",
    "Success is not about accolades, but about the lives you enrich with your ethical choices.",
    "A healthy relationship is rooted in honesty, trust, and a shared vision of success and happiness.",
    "True power is earned, not taken, and it thrives in a foundation of respect and ethical choices.",
    "Love is not something to possess; it is something to nurture, grow, and respect every day.",
    "Success comes when passion and hard work align, leading to outcomes that reflect your values.",
    "Great leaders build power not by forcing their will, but by empowering others with respect and support.",
    "In relationships and work, success is found in collaboration, not competition.",
    "The foundation of every great relationship is the mutual understanding that both are constantly evolving.",
    "Power is the ability to give others the tools to succeed and grow, not just to rule over them.",
    "True success is living a life where love, integrity, and purpose are the driving forces.",
    "Love without respect is fragile, but with respect, it can weather any storm.",
    "Success is not just about what you achieve, but how you impact the lives of those around you.",
    "The power of ethical choices in both love and work is that they create a legacy that lasts.",
    "To succeed in life, work, and relationships, one must be willing to grow, adapt, and stay true to their values.",
    "Success and power come to those who stay grounded in their values and stay true to their integrity.",
    "Love is about respect and care, not about controlling or changing someone else.",
    "In relationships, success is measured by the depth of connection, not the length of time together.",
    "True success comes when your work aligns with your passion and your relationships reflect your values.",
    "Power without integrity is fleeting, but true power lies in leading with humility and respect."
];

module.exports = quotes;
