const hadiths = [
  { hadith: "When Ramadan begins, the gates of Paradise are opened, the gates of Hell are closed, and the devils are chained.", numbering: "1/189", book: "Bukhari" },
  { hadith: "Fasting during Ramadan and six days of Shawwal is like fasting for a year.", numbering: "3/116", book: "Muslim" },
  { hadith: "The best fast after Ramadan is fasting in the month of Allah, al-Muharram.", numbering: "6/116", book: "Muslim" },
  { hadith: "Whoever stands in prayer during Ramadan with faith and seeking reward will have his past sins forgiven.", numbering: "1/189", book: "Bukhari" },
  { hadith: "Ramadan is the month in which the Qur'an was revealed.", numbering: "2/189", book: "Bukhari" },
  { hadith: "The fasting person has two moments of joy: when he breaks his fast and when he meets his Lord.", numbering: "2/665", book: "Muslim" },
  { hadith: "There is a gate in Paradise called Ar-Rayyan, through which only those who fast will enter.", numbering: "7/317", book: "Bukhari" },
  { hadith: "If someone eats or drinks forgetfully, he should complete his fast, for what he has eaten or drunk has been given to him by Allah.", numbering: "3/173", book: "Bukhari" },
  { hadith: "Whoever gives food for a fasting person to break their fast will have the same reward as the fasting person, without decreasing their reward.", numbering: "3/125", book: "Tirmidhi" },
  { hadith: "The five daily prayers, from one Friday prayer to the next Friday prayer, and from one Ramadan to the next Ramadan, are expiation for the sins committed in between, so long as major sins are avoided.", numbering: "1/349", book: "Muslim" },
  { hadith: "Whoever prays Qiyam during the nights of Ramadan out of faith and in hope of reward, his past sins will be forgiven.", numbering: "3/226", book: "Muslim" },
  { hadith: "Allah said: 'Every deed of the son of Adam is multiplied, but fasting is for Me, and I will reward it accordingly.'", numbering: "2/256", book: "Muslim" },
  { hadith: "The breath of a fasting person is sweeter to Allah than the fragrance of musk.", numbering: "2/189", book: "Bukhari" },
  { hadith: "Whoever fasts one day for the sake of Allah, Allah will keep his face away from Hellfire for seventy years.", numbering: "2/115", book: "Muslim" },
  { hadith: "Whoever provides iftar for a fasting person will earn the same reward, without diminishing the reward of the fasting person.", numbering: "2/37", book: "Tirmidhi" },
  { hadith: "Fasting is a shield; when one of you is fasting, let him not behave in an obscene manner.", numbering: "1/173", book: "Bukhari" },
  { hadith: "The du'a of a fasting person at the time of breaking the fast is not rejected.", numbering: "3/180", book: "Ibn Majah" },
  { hadith: "Seek Laylatul Qadr in the last ten nights of Ramadan.", numbering: "3/209", book: "Bukhari" },
  { hadith: "Laylatul Qadr is better than a thousand months.", numbering: "97:3", book: "Quran" },
  { hadith: "If anyone forgets that he is fasting and eats or drinks, let him complete his fast, for it is Allah who has fed him and given him drink.", numbering: "2/665", book: "Muslim" },
  { hadith: "The one who fasts with sincerity and hopes for reward will have his past sins forgiven.", numbering: "1/37", book: "Bukhari" },
  { hadith: "The Prophet would strive harder in worship during the last ten nights of Ramadan than at any other time.", numbering: "3/226", book: "Muslim" },
  { hadith: "Itikaf is to remain in the mosque and dedicate oneself to worship.", numbering: "2/231", book: "Bukhari" },
  { hadith: "He who does not give up false speech and evil actions, Allah is not in need of his leaving his food and drink.", numbering: "2/255", book: "Bukhari" },
  { hadith: "Whoever prays during Laylatul Qadr with faith and seeking reward will have his past sins forgiven.", numbering: "3/176", book: "Bukhari" },
  { hadith: "The most beloved deeds to Allah are those done consistently, even if they are small.", numbering: "1/692", book: "Bukhari" },
  { hadith: "Do not neglect Suhoor, for there is a blessing in it.", numbering: "2/49", book: "Bukhari" },
  { hadith: "The Prophet used to break his fast with fresh dates, or if none were available, with dry dates, or a sip of water.", numbering: "2/235", book: "Abu Dawood" },
  { hadith: "Fasting on the day of Ashura expiates the sins of the previous year.", numbering: "3/172", book: "Muslim" },
  { hadith: "Whoever fasts three days every month, it is as if he has fasted for a lifetime.", numbering: "2/295", book: "Bukhari" },
  { hadith: "The one who eats during the nights of Ramadan without fasting is like the one who breaks his fast before time.", numbering: "2/689", book: "Muslim" },
  { hadith: "Angels seek forgiveness for the fasting person until they break their fast.", numbering: "2/85", book: "Ibn Majah" },
  { hadith: "The best charity is given during Ramadan.", numbering: "3/317", book: "Tirmidhi" },
  { hadith: "Zakat ul-Fitr is purification for the fasting person from idle talk and obscenities.", numbering: "2/214", book: "Abu Dawood" },
  { hadith: "When one of you is fasting and someone insults him, let him say, ‘I am fasting.’", numbering: "2/233", book: "Bukhari" },
  { hadith: "It is not righteousness to fast while traveling if it causes difficulty.", numbering: "2/87", book: "Muslim" },
  { hadith: "O people, spread peace, feed others, and pray at night while people sleep, and you will enter Paradise in peace.", numbering: "2/246", book: "Tirmidhi" },
  { hadith: "The Prophet forbade fasting on Fridays alone unless one fasts the day before or after.", numbering: "3/66", book: "Bukhari" }
];

module.exports = hadiths;
