module.exports = {
    topics: [
        "Introduction to Graphic Design",
        "Principles of Design - Balance, Contrast, Alignment, Repetition, Proximity, Space",
        "Color Theory - RGB, CMYK, HSB, Hex Codes, Complementary Colors",
        "Typography - Serif vs. Sans-serif, Fonts, Kerning, Leading, Tracking",
        "Layout and Composition - Grid Systems, Rule of Thirds, White Space",
        "Visual Hierarchy and Emphasis",
        "Branding and Identity Design",
        "Logo Design Basics",
        "UI UX Fundamentals",
        "Typography Pairing and Readability",
        "Choosing the Right Fonts for a Project",
        "Working with Images and Graphics - Vector vs. Raster",
        "Understanding File Formats - JPG, PNG, SVG, EPS, PDF, AI, PSD",
        "Introduction to Design Software - Adobe Photoshop, Illustrator, Figma, Canva",
        "Basic Photo Editing and Retouching",
        "Creating Social Media Graphics",
        "Poster and Flyer Design",
        "Infographics and Data Visualization",
        "Icon Design Principles",
        "Packaging Design Basics",
        "Business Card and Stationery Design",
        "Website and App Design Basics",
        "Print Design vs. Digital Design",
        "Understanding DPI and Resolution",
        "Accessibility in Design - Color Blindness, Readability, UX Considerations",
        "Introduction to Motion Graphics",
        "Creating Simple Animations in Adobe After Effects",
        "Trends in Graphic Design - Minimalism, Flat Design, Skeuomorphism, etc.",
        "Design Thinking Process",
        "Client Communication and Presentation Skills",
        "Portfolio Building for Graphic Designers",
        "Freelancing and Career Paths in Graphic Design"
    ],
    mainDir: "Graphic Designing"
}
