module.exports = {
    topics: [
        "Introduction to ICT",
        "History and Evolution of ICT",
        "Components of a Computer System",
        "Hardware Basics",
        "Software Fundamentals",
        "Operating Systems Overview",
        "Introduction to Networking",
        "The Internet and World Wide Web",
        "Email and Online Communication",
        "Word Processing Applications",
        "Spreadsheet Basics",
        "Presentation Software",
        "Database Management Systems",
        "Graphics and Multimedia",
        "Introduction to Programming",
        "Web Development Basics",
        "Cybersecurity Essentials",
        "Ethics in ICT",
        "Digital Citizenship",
        "Cloud Computing Fundamentals",
        "Mobile Technology Overview",
        "Social Media Platforms",
        "E-commerce Basics",
        "ICT in Education",
        "ICT in Business",
        "Emerging Technologies",
        "Data Storage Solutions",
        "Introduction to Artificial Intelligence",
        "Virtual Reality and Augmented Reality",
        "Internet of Things (IoT)",
        "Computer Maintenance and Troubleshooting",
        "Networking Protocols and Standards",
        "Wireless Communication Technologies",
        "Introduction to Software Development",
        "Digital Marketing Fundamentals",
        "ICT Project Management",
        "Health and Safety in ICT",
        "Green Computing",
        "ICT Accessibility",
        "Open Source Software",
        "Introduction to Data Analytics",
        "ICT Career Opportunities"
    ],
    mainDir: "Introduction to ICT"
}
