module.exports = {
    topics: [
        "Understanding Social Dynamics",
        "Building Self-Esteem",
        "Effective Communication Skills",
        "Developing Empathy",
        "Active Listening Techniques",
        "Assertiveness Training",
        "Conflict Resolution Strategies",
        "Recognizing and Addressing Bullying",
        "Cyberbullying Awareness and Prevention",
        "Stress Management Techniques",
        "Emotional Intelligence Development",
        "Setting Personal Boundaries",
        "Cultivating Resilience",
        "Mindfulness and Self-Awareness",
        "Overcoming Social Anxiety",
        "Leadership Skills for Personal Growth",
        "Time Management and Organization",
        "Goal Setting and Achievement",
        "Developing a Growth Mindset",
        "Navigating Peer Pressure",
        "Building Healthy Relationships",
        "Self-Reflection Practices",
        "Understanding Body Language",
        "Public Speaking Confidence",
        "Developing Independence",
        "Embracing Authenticity",
        "Self-Discipline and Motivation",
        "Coping with Rejection",
        "Building a Support Network",
        "Understanding and Managing Emotions",
        "Developing Critical Thinking Skills",
        "Practicing Gratitude",
        "Enhancing Problem-Solving Abilities",
        "Understanding Personal Values",
        "Developing a Personal Code of Ethics",
        "Practicing Self-Care",
        "Balancing Personal and Social Life",
        "Understanding the Impact of Social Media",
        "Developing Patience and Tolerance",
        "Learning from Failure",
        "Practicing Humility",
        "Developing a Sense of Purpose",
        "Understanding Different Perspectives",
        "Building Trust with Others",
        "Practicing Forgiveness",
        "Developing Negotiation Skills",
        "Understanding the Role of Humor in Social Interactions",
        "Managing Expectations",
        "Developing Adaptability",
        "Embracing Lifelong Learning"
    ],
    mainDir: "Personal Development"
}
