module.exports = {
    topics: [
        "Electrostatics",
        "Electric Fields",
        "Gauss's Law",
        "Electric Potential",
        "Capacitance",
        "Current and Resistance",
        "Direct Current (DC) Circuits",
        "Magnetic Fields",
        "Sources of Magnetic Fields",
        "Electromagnetic Induction",
        "Inductance",
        "Alternating Current (AC) Circuits",
        "Maxwell's Equations",
        "Electromagnetic Waves",
        "Electrical Properties of Materials",
        "Semiconductor Physics",
        "Digital Circuits",
        "Analog Circuits",
        "Signal Processing",
        "Electromagnetic Compatibility",
        "Power Generation and Distribution",
        "Transformers",
        "Electric Motors and Generators",
        "Sensors and Actuators",
        "Wireless Communication",
        "Electromagnetic Interference",
        "Circuit Design and Analysis",
        "Microcontrollers and Embedded Systems",
        "Optoelectronics",
        "Quantum Electronics"
    ],
    mainDir: "Electricity and Magnetism (IT)"
}
