module.exports = {
    topics: [
        "The Boy Who Cried Wolf - The Importance of Honesty",
        "The Tortoise and the Hare - Slow and Steady Wins the Race",
        "The Fox and the Grapes - Dealing with Disappointment",
        "The Ant and the Grasshopper - Planning for the Future",
        "The Lion and the Mouse - Kindness is Never Wasted",
        "The Thirsty Crow - Problem-Solving and Perseverance",
        "The Goose that Laid the Golden Eggs - Greed Leads to Loss",
        "The Dog and the Bone - Being Content with What You Have",
        "The Fox and the Stork - Treat Others as You Want to Be Treated",
        "The Wolf in Sheep's Clothing - Appearances Can Be Deceiving",
        "The Crow and the Pitcher - Using Ingenuity to Overcome Challenges",
        "The North Wind and the Sun - Persuasion Over Force",
        "The Bundle of Sticks - Strength in Unity",
        "The Town Mouse and the Country Mouse - Appreciating Different Lifestyles",
        "The Fisherman and the Little Fish - A Little is Better Than Nothing",
        "The Wind and the Sun - Gentle Persuasion Wins Over Force",
        "The Two Frogs - The Dangers of Following Blindly",
        "The Fox and the Crow - Beware of Flattery",
        "The Donkey and the Load of Salt - Learning from Mistakes",
        "The Miser and His Gold - Wealth Unused is Worthless",
        "The Peacock and the Crane - True Worth is in Deeds, Not Appearance",
        "The Wolf and the Crane - Selfishness Repels Help",
        "The Oak and the Reeds - Flexibility Over Rigidity",
        "The Ass in the Lion's Skin - Pretending to Be What You're Not",
        "The Cat and the Mice - Cunning Can Be Dangerous",
        "The Farmer and His Sons - The Value of Hard Work",
        "The Fox and the Goat - Look Before You Leap",
        "The Hare and the Tortoise - Consistency Over Speed",
        "The Lark and Her Young Ones - Self-Reliance is Key",
        "The Lion's Share - The Nature of Greed",
        "The Milkmaid and Her Pail - Don't Count Your Chickens Before They Hatch",
        "The Monkey and the Dolphin - Honesty is the Best Policy",
        "The Mouse and the Frog - Harm Set, Harm Get",
        "The Old Man and Death - Be Careful What You Wish For",
        "The Shepherd's Boy - The Consequences of Lying",
        "The Wolf and the Lamb - Might Doesn't Make Right",
        "The Young Crab and His Mother - Lead by Example",
        "Belling the Cat - It's Easier Said Than Done",
        "The Ass and His Driver - Stubbornness Leads to Trouble",
        "The Bear and the Two Travelers - True Friends Stand by You",
        "The Crow and the Swan - Be Content with Who You Are",
        "The Dog in the Manger - Don't Deny Others What You Can't Have",
        "The Eagle and the Arrow - We Often Give Our Enemies the Means to Destroy Us",
        "The Fisher and the Little Fish - Better a Little Certainty Than a Great Chance",
        "The Frogs Desiring a King - Be Careful What You Wish For",
        "The Gnat and the Bull - We Are Often Unaware of Our Own Insignificance",
        "The Horse and the Groom - Appearance vs. Reality",
        "The Jay and the Peacock - Don't Pretend to Be What You're Not",
        "The Man and the Serpent - Returning Evil for Good",
        "The Mice in Council - Proposing is One Thing, Executing is Another"
    ],
    mainDir: "Moral Stories"
}